- name: ensure mariadb is installed
  apt:
    name:
      - mariadb-server
      - python3-mysqldb
    state: present

- name: create database wordpress
  community.mysql.mysql_db:
    name: "{{bd_name}}"
    state: present

- name: create user mysql wordpress
  community.mysql.mysql_user:
    name: "{{bd_user}}"
    host: "{{ item }}"
    password: "{{bd_pass}}"
    priv: "{{bd_name}}.*:ALL,GRANT"
  loop:
    - localhost

- name: mariadb listen in all interfaces
  lineinfile:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address            = 127.0.0.1"
    line: "bind-address            = 0.0.0.0"
    state: present
  notify: Reiniciar mariadb
    #-
