#cloud-config
hostname: ej5-server1

timezone: Europe/Madrid
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAA... sustituye esta línea por tu clave pública

chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text

package_update: true  # refresca índices de apt
package_upgrade: true # aplica actualizaciones disponibles en el primer arranque
